config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'

  resources :org_roles

  resources :customers

  resources :projects

  resources :project_activities

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'dashboards#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/project_activity.rb
class ProjectActivity < ActiveRecord::Base
  belongs_to :project
end

app/controllers/project_activities_controller.rb
class ProjectActivitiesController < ApplicationController
  before_action :set_project_activity, only: [:show, :edit, :update, :destroy]

  # GET /project_activities
  # GET /project_activities.json
  def index
    @project_activities = ProjectActivity.all
  end

  # GET /project_activities/1
  # GET /project_activities/1.json
  def show
  end

  # GET /project_activities/new
  def new
    @project_activity = ProjectActivity.new
  end

  # GET /project_activities/1/edit
  def edit
  end

  # POST /project_activities
  # POST /project_activities.json
  def create
    @project_activity = ProjectActivity.new(project_activity_params)

    respond_to do |format|
      if @project_activity.save
        format.html { redirect_to @project_activity, notice: 'Project activity was successfully created.' }
        format.json { render :show, status: :created, location: @project_activity }
      else
        format.html { render :new }
        format.json { render json: @project_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_activities/1
  # PATCH/PUT /project_activities/1.json
  def update
    respond_to do |format|
      if @project_activity.update(project_activity_params)
        format.html { redirect_to @project_activity, notice: 'Project activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_activity }
      else
        format.html { render :edit }
        format.json { render json: @project_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_activities/1
  # DELETE /project_activities/1.json
  def destroy
    @project_activity.destroy
    respond_to do |format|
      format.html { redirect_to project_activities_url, notice: 'Project activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_activity
      @project_activity = ProjectActivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_activity_params
      params.require(:project_activity).permit(:name, :start_date, :deliver_date, :project_id, :details)
    end
end

app/helpers/project_activities_helper.rb
module ProjectActivitiesHelper
end

app/views/project_activities/_form.html.erb
<%= form_for @project_activity, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :start_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deliver_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :deliver_date, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :details, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  project_activities_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/project_activities/edit.html.erb
<%- model_class = ProjectActivity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ProjectActivity %></h1>
</div>
<%= render :partial => 'form' %>

app/views/project_activities/index.html.erb
<%- model_class = ProjectActivity -%>
<div class="page-header">
  <h1><%=t '.title', :default => ProjectActivity %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:deliver_date) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @project_activities.each do |project_activity| %>
      <tr>
        <td><%= project_activity.id %></td>
        <td><%= project_activity.name %></td>
        <td><%= project_activity.start_date %></td>
        <td><%= project_activity.deliver_date %></td>
        <td><%= project_activity.details %></td>
        <td><%=l project_activity.created_at, format: :long %></td>
        <td>
          <%= link_to project_activity_path(project_activity), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to project_activity_path(project_activity), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_activity_path,
            :class => 'btn btn-primary' %>

app/views/project_activities/new.html.erb
<%- model_class = ProjectActivity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ProjectActivity %></h1>
</div>
<%= render :partial => 'form' %>

app/views/project_activities/show.html.erb
<%- model_class = ProjectActivity -%>
<div class="page-header">
  <h1><%=t '.title', :default => ProjectActivity %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @project_activity.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:start_date) %></dt>
      <dd><pre class="prettyprint"><%= @project_activity.start_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:deliver_date) %></dt>
      <dd><pre class="prettyprint"><%= @project_activity.deliver_date %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:details) %></dt>
      <dd><pre class="prettyprint"><%= @project_activity.details %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              project_activities_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_activity_path(@project_activity), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_activity_path(@project_activity),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>