config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'

  resources :org_roles

  resources :customers

  resources :projects

  resources :project_activities

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'dashboards#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/org_role.rb
class OrgRole < ActiveRecord::Base
  belongs_to :user
end

app/controllers/org_roles_controller.rb
class OrgRolesController < ApplicationController
  before_action :set_org_role, only: [:show, :edit, :update, :destroy]

  # GET /org_roles
  # GET /org_roles.json
  def index
    @org_roles = OrgRole.all
  end

  # GET /org_roles/1
  # GET /org_roles/1.json
  def show
  end

  # GET /org_roles/new
  def new
    @org_role = OrgRole.new
  end

  # GET /org_roles/1/edit
  def edit
  end

  # POST /org_roles
  # POST /org_roles.json
  def create
    @org_role = OrgRole.new(org_role_params)

    respond_to do |format|
      if @org_role.save
        format.html { redirect_to @org_role, notice: 'Org role was successfully created.' }
        format.json { render :show, status: :created, location: @org_role }
      else
        format.html { render :new }
        format.json { render json: @org_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /org_roles/1
  # PATCH/PUT /org_roles/1.json
  def update
    respond_to do |format|
      if @org_role.update(org_role_params)
        format.html { redirect_to @org_role, notice: 'Org role was successfully updated.' }
        format.json { render :show, status: :ok, location: @org_role }
      else
        format.html { render :edit }
        format.json { render json: @org_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /org_roles/1
  # DELETE /org_roles/1.json
  def destroy
    @org_role.destroy
    respond_to do |format|
      format.html { redirect_to org_roles_url, notice: 'Org role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_org_role
      @org_role = OrgRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_role_params
      params.require(:org_role).permit(:name, :manager, :user_id)
    end
end

app/helpers/org_roles_helper.rb
module OrgRolesHelper
end

app/views/org_roles/_form.html.erb
<%= form_for @org_role, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :manager, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :manager, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  org_roles_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/org_roles/edit.html.erb
<%- model_class = OrgRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => OrgRole %></h1>
</div>
<%= render :partial => 'form' %>

app/views/org_roles/index.html.erb
<%- model_class = OrgRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => OrgRole %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:manager) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @org_roles.each do |org_role| %>
      <tr>
        <td><%= org_role.id %></td>
        <td><%= org_role.name %></td>
        <td><%= org_role.manager %></td>
        <td><%=l org_role.created_at, format: :long %></td>
        <td>
          <%= link_to org_role_path(org_role), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to org_role_path(org_role), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_org_role_path,
            :class => 'btn btn-primary' %>

app/views/org_roles/new.html.erb
<%- model_class = OrgRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => OrgRole %></h1>
</div>
<%= render :partial => 'form' %>

app/views/org_roles/show.html.erb
<%- model_class = OrgRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => OrgRole %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @org_role.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:manager) %></dt>
      <dd><pre class="prettyprint"><%= @org_role.manager %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              org_roles_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_org_role_path(@org_role), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              org_role_path(@org_role),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>